In [1]:
# multi-class classification with Keras
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
# load dataset


In [2]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
import csv
# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
#Keras
import keras
from keras import models
from keras import layers


C:\Users\Chirag Periwal\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [3]:
import numpy as np
import pandas as pd
import scipy.io.wavfile as wav
from python_speech_features import mfcc
from tempfile import TemporaryFile
import os
import math
import pickle
import random
import operator

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import uniform, randint
import sklearn.metrics as skm
import sklearn.model_selection as skms
import sklearn.preprocessing as skp
from sklearn.linear_model import LogisticRegression
import sklearn.ensemble as ske

from pprint import pprint
import random
import librosa, IPython
import librosa.display as lplt
seed = 12
np.random.seed(seed)

In [7]:
# # generating a dataset
# header = 'filename chroma_stft rmse spectral_centroid spectral_bandwidth rolloff zero_crossing_rate'
# for i in range(1, 21):
#     header += f' mfcc{i}'
# header += ' label'
# header = header.split()

In [8]:
# file = open('data.csv', 'w', newline='')
# with file:
#     writer = csv.writer(file)
#     writer.writerow(header)
# genres = 'blues classical country disco hiphop jazz metal pop reggae rock'.split()

In [9]:
# for g in genres:
#     for filename in os.listdir(f'./gtzan/genres_original/{g}'):
#         songname = f'./gtzan/genres_original/{g}/{filename}'
#         print(songname)
#         y, sr = librosa.load(songname, mono=True, duration=30)
#         chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
#         rmse = librosa.feature.rms(y=y)
#         spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
#         spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
#         rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
#         zcr = librosa.feature.zero_crossing_rate(y)
#         mfcc = librosa.feature.mfcc(y=y, sr=sr)
#         to_append = f'{filename} {np.mean(chroma_stft)} {np.mean(rmse)} {np.mean(spec_cent)} {np.mean(spec_bw)} {np.mean(rolloff)} {np.mean(zcr)}'    
#         for e in mfcc:
#             to_append += f' {np.mean(e)}'
#         to_append += f' {g}'
#         file = open('data.csv', 'a', newline='')
#         with file:
#             writer = csv.writer(file)
#             writer.writerow(to_append.split())

In [7]:
dataframe = pd.read_csv("data.csv")
dataframe.head()

filename  chroma_stft      rmse  spectral_centroid  \
0  blues.00000.wav     0.349951  0.130192        1784.416546   
1  blues.00001.wav     0.340945  0.095892        1529.871314   
2  blues.00002.wav     0.363562  0.175494        1552.637786   
3  blues.00003.wav     0.404848  0.141139        1070.110059   
4  blues.00004.wav     0.308598  0.091540        1835.507009   

   spectral_bandwidth      rolloff  zero_crossing_rate       mfcc1  \
0         2002.657106  3806.418650            0.083066 -113.619385   
1         2038.612143  3548.986873            0.056044 -207.581512   
2         1747.382028  3041.089944            0.076301  -90.776344   
3         1596.244204  2185.061787            0.033309 -199.462006   
4         1748.367477  3581.003346            0.101500 -160.291855   

        mfcc2      mfcc3  ...    mfcc12    mfcc13    mfcc14    mfcc15  \
0  121.553017 -19.151056  ...  8.806787 -3.665802  5.745939 -5.161711   
1  123.997147   8.939115  ...  5.375942 -2.237833  4.217125 -6.011047   
2  140.448608 -29.100559  ...  5.785763 -8.899733 -1.087024 -9.216774   
3  150.094727   5.649167  ...  6.085354 -2.476188 -1.076225 -2.876056   
4  126.195763 -35.602501  ... -2.809849 -6.935621 -7.559294 -9.172152   

     mfcc16    mfcc17    mfcc18    mfcc19     mfcc20  label  
0  0.750298 -1.688358 -0.409329 -2.298869   1.219947  blues  
1  0.932668 -0.717028  0.292333 -0.285717   0.532144  blues  
2  2.453649 -7.721793 -1.816497 -3.434353  -2.231391  blues  
3  0.776909 -3.320055  0.637263 -0.617507  -3.406940  blues  
4 -4.510408 -5.453736 -0.924468 -4.408076 -11.701833  blues  

[5 rows x 28 columns]

In [8]:
dataset = dataframe.values
X = dataset[:,1:27].astype(float)

In [9]:
genre_list = dataframe.iloc[:, -1]
encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)



In [10]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
X_train.shape


(799, 26)

In [15]:
X_test.shape

(200, 26)

In [16]:
from xgboost import XGBClassifier
classifier = XGBClassifier(use_label_encoder =False)
classifier.fit(X_train, y_train)

C:\Users\Chirag Periwal\anaconda3\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


[04:26:46] WARNING: C:\Windows\Temp\abs_557yfx631l\croots\recipe\xgboost-split_1659548953302\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=12,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
              subsample=1, tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 8  0  1  0  0  1  3  0  0  1]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 1  2 11  3  0  3  0  0  0  6]
 [ 1  0  0 10  2  2  1  0  0  8]
 [ 0  0  0  2 17  0  4  1  2  1]
 [ 0  2  1  0  0 12  0  0  1  0]
 [ 1  0  0  1  0  0 16  0  0  0]
 [ 0  0  0  1  2  2  0 15  2  1]
 [ 1  0  1  1  4  0  0  0 12  2]
 [ 1  0  1  3  0  4  2  0  0  9]]


0.605

In [50]:
import random
from scipy.stats import uniform
seed=12
xgb_model = XGBClassifier(n_estimators=100, random_state=seed)
xgb_params = {
    "colsample_bytree": uniform(0.7, 0.3),
    "gamma": uniform(0, 0.5),
    "learning_rate": uniform(0.03, 0.3), # default 0.1 
    "max_depth": random.randint(2, 6), # default 3
    "n_estimators": random.randint(100, 150), # default 100
    "subsample": (0.6, 0.4)
}


In [53]:
 from sklearn.model_selection import RandomizedSearchCV
# Use the random grid to search for best hyperparameters
xgb_random = skms.RandomizedSearchCV(estimator = xgb_model, param_distributions=xgb_params, n_iter=20, cv = 3, verbose=2, n_jobs = -1, random_state=seed, scoring='f1_weighted', return_train_score=True)
# Fit the random search model
xgb_random.fit(X_train, y_train)

TypeError: Parameter value is not iterable or distribution (key='max_depth', value=5)

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = xgb_random.best_estimator_.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

AttributeError: 'RandomizedSearchCV' object has no attribute 'best_estimator_'

In [22]:
 import catboost as ctb

In [23]:
model_CBC = ctb.CatBoostClassifier()
model_CBC.fit(X_train, y_train)
print(model_CBC)

Learning rate set to 0.078226
0:	learn: 2.2300039	total: 303ms	remaining: 5m 2s
1:	learn: 2.1581403	total: 388ms	remaining: 3m 13s
2:	learn: 2.1063306	total: 467ms	remaining: 2m 35s
3:	learn: 2.0439938	total: 553ms	remaining: 2m 17s
4:	learn: 1.9928596	total: 644ms	remaining: 2m 8s
5:	learn: 1.9331744	total: 722ms	remaining: 1m 59s
6:	learn: 1.8846170	total: 808ms	remaining: 1m 54s
7:	learn: 1.8421919	total: 901ms	remaining: 1m 51s
8:	learn: 1.8029360	total: 1s	remaining: 1m 50s
9:	learn: 1.7673553	total: 1.09s	remaining: 1m 47s
10:	learn: 1.7362114	total: 1.15s	remaining: 1m 43s
11:	learn: 1.7070206	total: 1.21s	remaining: 1m 39s
12:	learn: 1.6760002	total: 1.27s	remaining: 1m 36s
13:	learn: 1.6430516	total: 1.33s	remaining: 1m 33s
14:	learn: 1.6171105	total: 1.39s	remaining: 1m 31s
15:	learn: 1.5907128	total: 1.44s	remaining: 1m 28s
16:	learn: 1.5630643	total: 1.5s	remaining: 1m 26s
17:	learn: 1.5364454	total: 1.55s	remaining: 1m 24s
18:	learn: 1.5128086	total: 1.61s	remaining: 1m 23

163:	learn: 0.5335655	total: 9.38s	remaining: 47.8s
164:	learn: 0.5305987	total: 9.43s	remaining: 47.7s
165:	learn: 0.5289176	total: 9.48s	remaining: 47.6s
166:	learn: 0.5265946	total: 9.53s	remaining: 47.5s
167:	learn: 0.5242240	total: 9.59s	remaining: 47.5s
168:	learn: 0.5215712	total: 9.65s	remaining: 47.5s
169:	learn: 0.5190075	total: 9.71s	remaining: 47.4s
170:	learn: 0.5162915	total: 9.77s	remaining: 47.4s
171:	learn: 0.5137591	total: 9.83s	remaining: 47.3s
172:	learn: 0.5104903	total: 9.88s	remaining: 47.2s
173:	learn: 0.5086505	total: 9.93s	remaining: 47.2s
174:	learn: 0.5062855	total: 9.98s	remaining: 47.1s
175:	learn: 0.5033909	total: 10s	remaining: 47s
176:	learn: 0.5010080	total: 10.1s	remaining: 46.9s
177:	learn: 0.4988604	total: 10.1s	remaining: 46.8s
178:	learn: 0.4960252	total: 10.2s	remaining: 46.7s
179:	learn: 0.4939421	total: 10.2s	remaining: 46.7s
180:	learn: 0.4923925	total: 10.3s	remaining: 46.6s
181:	learn: 0.4908569	total: 10.3s	remaining: 46.5s
182:	learn: 0.48

324:	learn: 0.2825098	total: 17.7s	remaining: 36.8s
325:	learn: 0.2816259	total: 17.7s	remaining: 36.7s
326:	learn: 0.2808229	total: 17.8s	remaining: 36.6s
327:	learn: 0.2801207	total: 17.8s	remaining: 36.6s
328:	learn: 0.2794098	total: 17.9s	remaining: 36.5s
329:	learn: 0.2784848	total: 17.9s	remaining: 36.4s
330:	learn: 0.2778238	total: 18s	remaining: 36.4s
331:	learn: 0.2766238	total: 18.1s	remaining: 36.3s
332:	learn: 0.2756388	total: 18.1s	remaining: 36.3s
333:	learn: 0.2747050	total: 18.2s	remaining: 36.2s
334:	learn: 0.2734440	total: 18.2s	remaining: 36.1s
335:	learn: 0.2729573	total: 18.2s	remaining: 36.1s
336:	learn: 0.2720651	total: 18.3s	remaining: 36s
337:	learn: 0.2709287	total: 18.3s	remaining: 35.9s
338:	learn: 0.2698017	total: 18.4s	remaining: 35.9s
339:	learn: 0.2690852	total: 18.4s	remaining: 35.8s
340:	learn: 0.2682661	total: 18.5s	remaining: 35.7s
341:	learn: 0.2673645	total: 18.5s	remaining: 35.7s
342:	learn: 0.2665914	total: 18.6s	remaining: 35.6s
343:	learn: 0.26

484:	learn: 0.1766674	total: 26s	remaining: 27.6s
485:	learn: 0.1764598	total: 26.1s	remaining: 27.6s
486:	learn: 0.1759043	total: 26.1s	remaining: 27.5s
487:	learn: 0.1754195	total: 26.2s	remaining: 27.5s
488:	learn: 0.1751094	total: 26.2s	remaining: 27.4s
489:	learn: 0.1743647	total: 26.3s	remaining: 27.4s
490:	learn: 0.1738148	total: 26.3s	remaining: 27.3s
491:	learn: 0.1733276	total: 26.4s	remaining: 27.2s
492:	learn: 0.1730217	total: 26.4s	remaining: 27.2s
493:	learn: 0.1725453	total: 26.5s	remaining: 27.1s
494:	learn: 0.1721223	total: 26.5s	remaining: 27.1s
495:	learn: 0.1718136	total: 26.6s	remaining: 27s
496:	learn: 0.1715033	total: 26.6s	remaining: 27s
497:	learn: 0.1709519	total: 26.7s	remaining: 26.9s
498:	learn: 0.1706643	total: 26.7s	remaining: 26.8s
499:	learn: 0.1703612	total: 26.8s	remaining: 26.8s
500:	learn: 0.1699507	total: 26.8s	remaining: 26.7s
501:	learn: 0.1694700	total: 26.9s	remaining: 26.7s
502:	learn: 0.1690617	total: 26.9s	remaining: 26.6s
503:	learn: 0.1687

643:	learn: 0.1219399	total: 34.4s	remaining: 19s
644:	learn: 0.1217575	total: 34.5s	remaining: 19s
645:	learn: 0.1215432	total: 34.5s	remaining: 18.9s
646:	learn: 0.1213708	total: 34.6s	remaining: 18.9s
647:	learn: 0.1211099	total: 34.7s	remaining: 18.8s
648:	learn: 0.1209236	total: 34.7s	remaining: 18.8s
649:	learn: 0.1205148	total: 34.8s	remaining: 18.7s
650:	learn: 0.1203866	total: 34.8s	remaining: 18.7s
651:	learn: 0.1201595	total: 34.9s	remaining: 18.6s
652:	learn: 0.1199695	total: 34.9s	remaining: 18.6s
653:	learn: 0.1198172	total: 35s	remaining: 18.5s
654:	learn: 0.1196429	total: 35s	remaining: 18.4s
655:	learn: 0.1194372	total: 35.1s	remaining: 18.4s
656:	learn: 0.1191890	total: 35.1s	remaining: 18.3s
657:	learn: 0.1189784	total: 35.2s	remaining: 18.3s
658:	learn: 0.1187676	total: 35.3s	remaining: 18.2s
659:	learn: 0.1186391	total: 35.3s	remaining: 18.2s
660:	learn: 0.1185298	total: 35.4s	remaining: 18.1s
661:	learn: 0.1183166	total: 35.4s	remaining: 18.1s
662:	learn: 0.118078

805:	learn: 0.0911770	total: 43s	remaining: 10.3s
806:	learn: 0.0910370	total: 43s	remaining: 10.3s
807:	learn: 0.0908958	total: 43.1s	remaining: 10.2s
808:	learn: 0.0907366	total: 43.1s	remaining: 10.2s
809:	learn: 0.0906052	total: 43.2s	remaining: 10.1s
810:	learn: 0.0904662	total: 43.3s	remaining: 10.1s
811:	learn: 0.0903321	total: 43.3s	remaining: 10s
812:	learn: 0.0901771	total: 43.4s	remaining: 9.97s
813:	learn: 0.0900709	total: 43.4s	remaining: 9.92s
814:	learn: 0.0899828	total: 43.5s	remaining: 9.86s
815:	learn: 0.0898187	total: 43.5s	remaining: 9.81s
816:	learn: 0.0897370	total: 43.6s	remaining: 9.76s
817:	learn: 0.0896863	total: 43.6s	remaining: 9.7s
818:	learn: 0.0895855	total: 43.7s	remaining: 9.65s
819:	learn: 0.0894227	total: 43.7s	remaining: 9.59s
820:	learn: 0.0893321	total: 43.8s	remaining: 9.54s
821:	learn: 0.0891993	total: 43.8s	remaining: 9.48s
822:	learn: 0.0889901	total: 43.9s	remaining: 9.43s
823:	learn: 0.0888664	total: 43.9s	remaining: 9.38s
824:	learn: 0.08876

966:	learn: 0.0717532	total: 51.3s	remaining: 1.75s
967:	learn: 0.0716664	total: 51.4s	remaining: 1.7s
968:	learn: 0.0715908	total: 51.4s	remaining: 1.64s
969:	learn: 0.0714937	total: 51.5s	remaining: 1.59s
970:	learn: 0.0713784	total: 51.5s	remaining: 1.54s
971:	learn: 0.0713500	total: 51.6s	remaining: 1.49s
972:	learn: 0.0712257	total: 51.6s	remaining: 1.43s
973:	learn: 0.0711446	total: 51.7s	remaining: 1.38s
974:	learn: 0.0710264	total: 51.7s	remaining: 1.33s
975:	learn: 0.0709734	total: 51.8s	remaining: 1.27s
976:	learn: 0.0708525	total: 51.8s	remaining: 1.22s
977:	learn: 0.0707856	total: 51.9s	remaining: 1.17s
978:	learn: 0.0706661	total: 51.9s	remaining: 1.11s
979:	learn: 0.0705712	total: 52s	remaining: 1.06s
980:	learn: 0.0704977	total: 52s	remaining: 1.01s
981:	learn: 0.0704471	total: 52.1s	remaining: 955ms
982:	learn: 0.0703776	total: 52.1s	remaining: 902ms
983:	learn: 0.0702941	total: 52.2s	remaining: 849ms
984:	learn: 0.0701230	total: 52.2s	remaining: 795ms
985:	learn: 0.070

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = model_CBC.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[12  0  0  0  0  0  1  0  0  1]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 5  1 11  2  0  2  0  1  1  3]
 [ 0  0  0 18  2  1  0  0  0  3]
 [ 0  0  0  2 18  0  2  1  3  1]
 [ 0  0  0  0  0 15  0  0  1  0]
 [ 1  0  0  1  0  0 16  0  0  0]
 [ 0  1  0  0  2  2  0 16  2  0]
 [ 0  0  1  0  4  0  0  0 14  2]
 [ 2  0  1  3  0  2  2  0  1  9]]


0.7

In [27]:
songname='./gtzan/hip-hop-rock-beats-118000.wav'
def feature_extract(songname):
    y, sr = librosa.load(songname, mono=True, duration=30)
    chroma_stft = librosa.feature.chroma_stft(y=y, sr=sr)
    rmse = librosa.feature.rms(y=y)
    spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
    spec_bw = librosa.feature.spectral_bandwidth(y=y, sr=sr)
    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
    zcr = librosa.feature.zero_crossing_rate(y)
    mfcc = librosa.feature.mfcc(y=y, sr=sr)
    to_append = f'{np.mean(chroma_stft)} {np.mean(rmse)} {np.mean(spec_cent)} {np.mean(spec_bw)} {np.mean(rolloff)} {np.mean(zcr)}'    
    for e in mfcc:
        to_append += f' {np.mean(e)}'
    # to_append
    li = list(to_append.split(" "))
    li=[float(i) for i in li]
    return li



In [28]:
li=feature_extract(songname)

In [33]:
def predict(li):
    results = {1: 'blues', 2: 'classical', 3: 'country', 4: 'disco', 5: 'hiphop', 6: 'jazz', 7: 'metal', 8: 'pop', 9: 'reggae', 10: 'rock'}
    number=classifier.predict([li])[0]
    return results[number+1]

In [34]:
predict(li)

'hiphop'

In [31]:
import pickle


In [ ]:
# # create an iterator object with write permission - model.pkl
# pickle.dump(classifier,open('classifier.pkl','wb'))

In [ ]:
# pickle.dump(xgb_random.best_estimator_,open('xgb.pkl','wb'))